### ISSUE TITLE
Would be cool if it would work with special slots like those of Scout mod or Trinkets

### ISSUE THREAD

**Issue by Azarilh** [WerDei/Zoomglass#4] opened 2022-07-23 19:41 UTC
My idea was to equip the spyglass as a trinket with the Trinkets slot, but this mod can't locate the spyglass in the trinket slot.

**Comment by WerDei** [comment] 2022-07-24 10:54
Duplicate of #3

**Closed as not planned by WerDei** 2022-07-24 10:54 UTC
